name: liteMacro CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

# Cancel previous in-progress runs for the same ref (useful for PR updates)
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test:
    name: Build & Test (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Adjust the Java versions as needed for your project
        java: ["21"]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build (includes tests & checks)
        run: ./gradlew --no-daemon build --stacktrace

      - name: Upload test reports (always)
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: test-reports-java${{ matrix.java }}
          path: |
            **/build/test-results/test/**
            **/build/reports/tests/test/**

      - name: Upload built jars (if any)
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: build-artifacts-java${{ matrix.java }}
          path: |
            **/build/libs/*.jar
            !**/*-sources.jar
            !**/*-javadoc.jar
